[package]
name = "sky-lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1.0.14"
lazy_static = "1.4.0"
heapless = "0.8.0"
